#!/bin/bash

USUARIO=pablorh
FECHA=$(date +%Y%m%d_%H%M%S)
BACKUP_DIR="/home/p2l2"
NOMBRE_BACKUP="backup_${FECHA}.tar.gz"

mysqldump -u root -p myDB > $BACKUP_DIR/backup_BD_$FECHA.sql

tar czf $BACKUP_DIR/$NOMBRE_BACKUP \
	$BACKUP_DIR/backup_BD_$FECHA.sql \

rm $BACKUP_DIR/backup_BD_$FECHA.sql

echo "Backup aparcao en $BACKUP_DIR"
